# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   port: 5433

# development:
#   <<: *default
#   database: apañame_development

# test:
#   <<: *default
#   database: apañame_test

# production:
#   <<: *default
#   database: apañame_production
#   username: apañame
#   password: <%= ENV['APAÑAME_DATABASE_PASSWORD'] %>
#   port: 5432

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_finalg34
  username: rodrigo
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5433

test:
  <<: *default
  database: test_finalg34
  username: rodrigo
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5433

production:
  <<: *default
  database: production__finalg34
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['USERNAME_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>